//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tovan_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_images
    {
        public int imageID { get; set; }
        public string imageSrc { get; set; }
        public Nullable<int> imageCategory { get; set; }
    
        public virtual Tbl_category Tbl_category { get; set; }
    }
}
